- name: Variables Testing
  hosts: dev
  vars:
    NAME: "Venkat"
    COURSE: "DevOps with AWS"
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: Hello {{NAME}} welcome to {{COURSE}} Course
        msg: "Hello {{NAME}} welcome to {{COURSE}}"

  # - name: print the information again
  #   vars: #task level variables override play level
  #     COURSE: "Ansible"
  #   ansible.builtin.debug:
  #     msg: "Hello {{NAME}} welcome to {{COURSE}}""
