- name: Variables Testing
  hosts: dev
  vars:
    NAME: "Venkat"
    COURSE: "DevOps with AWS"
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: Hello {{NAME}} welcome to {{COURSE}} Course
  
  - name: print information again 
    vars:
      NAME: "Suresh"
      COURSE: "Ansible"
    ansible.builtin.debug:
      msg: Hello {{NAME}} welcome to {{COURSE}} Course
